{% set name = "phz_nnpz" %}
{% set version = "1.4.1" %}
{% set tagversion = "1.4.1" %}
{% set build_number = 6 %}

package:
    name: {{ name|lower }}
    version: {{ version }} 

source:
    git_rev: {{ tagversion }}
    git_url: https://github.com/astrorama/PHZ_NNPZ.git

build:
    number: {{ build_number }}
    run_exports:
      - {{ pin_subpackage('phz_nnpz', max_pin='x.x.x') }}

requirements:
    build:
        - python                             # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - libcxx<16
        - cfitsio >=3.470
    host:
        - python
        - boost 
        - libcxx<16
        - alexandria ==2.31.3
        - cfitsio >=3.470
        - CCfits >=2.5
        - pybind11 >=2.6
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('libcxx', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('cfitsio', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('CCfits', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('astropy', min_pin='x.x', max_pin='x') }}
        - fitsio
        - matplotlib
        - scipy
        - requests
        - scikit-learn

test:
    commands:
        - $PREFIX/bin/NnpzCompleteReferenceSample --version

about:
    home: https://github.com/astrorama/PHZ_NNPZ.git
    license: LGPL
    license_file: LICENSE
    summary: SDC-CH Nearest Neighbor Photometric Redshift Tool

