github:
  user_or_org: astrorama 
  tooling_branch_name: main

test_on_native_only: true

build_platform:
  osx_arm64: osx_64

provider:
  linux: azure
  osx: azure
  win: None

azure:
  store_build_artifacts: False

secrets: ["GIT_USER", "GIT_TOKEN"]

recipe_dir: recipe

skip_render:
  - README.md
  - LICENSE.txt
  - LICENSE
  - .gitignore
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/workflows

